### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by mariushosting** [goshops-com/clipshare#12]
Is there any Docker support plan?

**Comment by sjcotto** [comment]
Hi @mariushosting 

Clipshare is a desktop app that publish videos directly to a S3-compatible storage and provides a URL to share, so no need for docker or any server hosting, we do have a docker compose as an example if someone wants to use minio instead of a S3 provider

**Comment by sjcotto** [comment]
going to close it but please reply if u have any other related question to this or something is not clear
