### ISSUE TITLE
Creating new tray..........

### ISSUE THREAD

**Issue by gabovj** [goshops-com/clipshare#13]
```
oi@fedora:~/Documents/clipshare$ npm start

> clipshare@1.0.0 start
> electron .

(node:501750) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `electron --trace-warnings ...` to show where the warning was created)
App is ready
Creating new tray
Tray already exists, destroying old tray
Creating new tray
```

after this what should i do?

**Comment by sjcotto** [comment]
hi, do u see any errors? if not you should see a tray icon

**Comment by sjcotto** [comment]
if no error but icon don't appear, what operating system are u using?

**Comment by gabovj** [comment]
no error and no icon, i am using Fedora 40

**Comment by sjcotto** [comment]
What gui, gnome/kde?

**Comment by gabovj** [comment]
GNOME Shell 46.4

**Comment by sjcotto** [comment]
Thanks, going to install a VM and test

**Comment by sjcotto** [comment]
interesting stuff, seems like gnome dosen't support tray icons anymore, there are a few extentions to add it

for example: https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

**Comment by gabovj** [comment]
i will give it a try, let you know

**Comment by sjcotto** [comment]
Another thing I was thinking is to have a way to start it without tray
icon, like open the window directly for OS that dosent have tray icons or
users tha don't want it maybe is a good idea not sure, do u have a opinion
on this?

**Comment by gabovj** [comment]
it would be nice that option

**Comment by sjcotto** [comment]
ok, i just added this new env variable, it can be tested from the branch `window-mode` 

here is a quick demo from virtual box: https://clipshare.gopersonal.com/01J6T7WE38H4893JWYYKQQNZ8X.webm

please confirm if this works for you from this branch and i will merge the PR, the new enviroment variable is

```
MODE=WINDOW
```

**Comment by gabovj** [comment]
It works perfect, thank you so much

**Comment by sjcotto** [comment]
Great news, PR merged

Thanks
