### ISSUE TITLE
Add Validation for Critical Environment Variables in .env File

### ISSUE THREAD

**Issue by mcruvinel** [goshops-com/clipshare#15]
Currently, the application does not validate whether critical environment variables in the .env file are properly set. This lack of validation can lead to runtime errors and unexpected behavior if required configuration values are missing.

To address this issue, we need to implement a validation mechanism to ensure that all critical environment variables are present and correctly configured before the application starts. This will help in preventing issues related to missing or incorrect configuration settings and improve the overall reliability of the application.

I will open a pull request now

**Comment by mcruvinel** [comment]
https://github.com/goshops-com/clipshare/pull/16

**Comment by sjcotto** [comment]
great idea

**Comment by sjcotto** [comment]
@mcruvinel can u do the change commented on the PR?

**Comment by mcruvinel** [comment]
> @mcruvinel can u do the change commented on the PR?

Yes, i just did now.
https://github.com/goshops-com/clipshare/pull/18

**Comment by sjcotto** [comment]
thanks
